(ns dev.jeroenvandijk.chess.validator.cvx
  (:require [clojure.java.io :as io]
            [edamame.core :as edamame]))


(def header (str "
;; -*- mode: clojure -*-
;; vim: syntax=clojure 

;; --- DO NOT EDIT - AUTOMATICALLY GENERATED BY "
                 (clojure.string/replace *file* (System/getenv "PWD") "") 
                 " --- 
"))


(def namespace-dir "dev/jeroenvandijk/chess/validator")


(defn get-file-content [file]
  (slurp (clojure.java.io/resource (str namespace-dir "/" file))))


(defn code-forms []
  (let [content (str (get-file-content "clj_compatibility.cljc")
                     "\n"
                     (get-file-content "clj.cljc"))
        forms
        (edamame/parse-string-all content
                                  {;; Macros
                                   :syntax-quote true

                                    ;; Function macro %
                                   :fn true

                                   :features #{:cvx} :read-cond :allow})]
    (->> forms
         (remove #(= (first %) 'comment)))))

(declare optimized-code-forms)

(defn generate
  ([]
   (generate (str "src/" namespace-dir "/chess.cvx")))

  ([f]
   (spit f (str header (clojure.string/join "\n\n" (map pr-str (optimized-code-forms)))))))


(comment
  (generate)
  :-)


;; Trickery to inline big datastructures in chess.cvx
(require '[dev.jeroenvandijk.chess.validator.clj
           :as validator
           :refer [map-positions
                   king-deltas
                   knight-deltas
                   rook-deltas
                   bishop-deltas
                   queen-deltas
                   rays
                   map-ranks

                   bishop-directions
                   rook-directions

                   black-pawn-double-push
                   white-pawn-double-push
                   ; black-pawn-positions
                   ; white-pawn-positions
                   ; black-pawn-captures
                   ;white-pawn-captures
                   all-positions
                   index->file+rank
                   betweens
                   file+rank->index
                   direction

                   white-double-push-ep
                   black-double-push-ep]]
         '[clojure.set :refer [union]])

(defn inline-form [v form]
  (let [current-ns (ns-name *ns*)]
    (try
      (concat v [(list 'quote (eval (list 'do '(in-ns 'dev.jeroenvandijk.chess.validator.clj) (last form))))])
      (finally 
        (in-ns current-ns)))))


(defn optimized-code-forms []
  (map (fn [form]
         (let [v (take 2 form)]
           (condp = v
             '(def bishop-deltas) (inline-form v form)
             '(def rook-deltas) (inline-form v form)
             '(def queen-deltas) (inline-form v form)
             '(def all-positions) (inline-form v form)
             '(def king-positions) (inline-form v form)
             '(def knight-positions) (inline-form v form)
             '(def rook-positions) (inline-form v form)
             '(def bishop-positions) (inline-form v form)
             '(def queen-positions) (inline-form v form)
             '(def black-pawn-positions) (inline-form v form)
             '(def white-pawn-positions) (inline-form v form)
             '(def black-pawn-captures) (inline-form v form)
             '(def white-pawn-captures) (inline-form v form)
             '(def white-pawn-double-push) (inline-form v form)
             '(def black-pawn-double-push) (inline-form v form)
  
             '(def white-double-push-ep (inline-form v form))
             '(def black-double-push-ep (inline-form v form))
  
             '(def tiles-between) (inline-form v form) ; 23M juice
             '(def direction-between) (inline-form v form) ; 6M juice
             form)))
       (code-forms)))
  

